# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - package
  - publish

build-keycloak-authServices-authentication-nuget:
  stage: package
  script:
    - dotnet pack -c Release --output ./nupkgs ./src/Keycloak.AuthServices.Authentication/
  artifacts:
    paths:
      - ./nupkgs/*.nupkg
  only:
    - main

build-keycloak-authServices-authorization-nuget:
  stage: package
  script:
    - dotnet pack -c Release --output ./nupkgs ./src/Keycloak.AuthServices.Authorization/
  artifacts:
    paths:
      - ./nupkgs/*.nupkg
  only:
    - main

build-keycloak-authServices-common-nuget:
  stage: package
  script:
    - dotnet pack -c Release --output ./nupkgs ./src/Keycloak.AuthServices.Common/
  artifacts:
    paths:
      - ./nupkgs/*.nupkg
  only:
    - main

build-keycloak-authServices-sdk-nuget:
  stage: package
  script:
    - dotnet pack -c Release --output ./nupkgs ./src/Keycloak.AuthServices.Sdk/
  artifacts:
    paths:
      - ./nupkgs/*.nupkg
  only:
    - main

publish:
  stage: publish
  image: mcr.microsoft.com/dotnet/sdk:latest
  script:
    - dotnet nuget list source | grep -q 'signator-common-repo' && dotnet nuget remove source signator-common-repo || echo "Source doesn't exist"
    # We are pushing all packages to the same repository with the id: 51 (The actual project is "Signator Common")
    - dotnet nuget add source "${CI_API_V4_URL}/projects/51/packages/nuget/index.json" --name signator-common-repo --username gitlab-ci-token --password ${CI_JOB_TOKEN} --store-password-in-clear-text
    - dotnet nuget push "./nupkgs/*.nupkg" --source signator-common-repo

